name: CI
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh workflow run --repo wojtekmach/private_actions ci.yml -f wxwidgets-version=3.1.7 -f otp-version=25.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
